// 两个渲染进程共用的桥
const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("vf", {
  setIgnore: (v) => ipcRenderer.send("vf-ignore", v),
  draggingSet: (v) => ipcRenderer.send("vf-dragging", v),
  pillWidth: (w) => ipcRenderer.send("vf-pill-w", w),
  moveBy: (dx, dy) => ipcRenderer.send("vf-move-by", { dx, dy }),
  resizeBy: (edge, dx, dy) => ipcRenderer.send("vf-resize-by", { edge, dx, dy }),
  geomSave: () => ipcRenderer.send("vf-geom-save"),
  capture: () => ipcRenderer.invoke("vf-capture"),
  recInfo: () => ipcRenderer.invoke("vf-rec-info"),
  recFileStart: () => ipcRenderer.invoke("vf-rec-file-start"),
  recChunk: (buf) => ipcRenderer.send("vf-rec-chunk", buf),
  recFileEnd: (keep) => ipcRenderer.invoke("vf-rec-file-end", keep),
  flash: () => ipcRenderer.send("vf-flash"),
  onFlash: (cb) => ipcRenderer.on("vf-flash", cb),
  confGet: () => ipcRenderer.invoke("conf-get"),
  lockSet: (v) => ipcRenderer.send("vf-lock-set", v),
  onLock: (cb) => ipcRenderer.on("vf-lock", (_e, v) => cb(v)),
  fullscreenSet: (v) => ipcRenderer.send("vf-fullscreen-set", v),
  onFullscreen: (cb) => ipcRenderer.on("vf-fullscreen", (_e, v) => cb(v)),
  takeoverSet: (v) => ipcRenderer.invoke("vf-takeover-set", v),
  onTakeover: (cb) => ipcRenderer.on("vf-takeover", (_e, s) => cb(s)),
  action: (a) => ipcRenderer.invoke("vf-action", a),
  gameControlSet: (v) => ipcRenderer.invoke("vf-game-control-set", v),
  gameStatus: (refresh = false) => ipcRenderer.invoke("vf-game-status", refresh),
  gameAction: (a) => ipcRenderer.invoke("vf-game-action", a),
  onGameControl: (cb) => ipcRenderer.on("vf-game-control", (_e, s) => cb(s)),
  onTheme: (cb) => ipcRenderer.on("vf-theme", (_e, t) => cb(t)),
  themeImport: () => ipcRenderer.invoke("theme-import"),
  themeExport: () => ipcRenderer.invoke("theme-export"),
  themeReset: () => ipcRenderer.send("theme-reset"),
  setInset: (px) => ipcRenderer.send("vf-inset", px),
  confSet: (c) => ipcRenderer.invoke("conf-set", c),
  connState: (s) => ipcRenderer.send("vf-conn-state", s),
  onConnState: (cb) => ipcRenderer.on("vf-conn-state", (_e, s) => cb(s)),
  panelCmd: (cmd) => ipcRenderer.send("vf-panel-cmd", cmd),
  onPanelCmd: (cb) => ipcRenderer.on("vf-panel-cmd", (_e, c) => cb(c)),
  quit: () => ipcRenderer.send("vf-quit"),
});
